//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportCenso.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class alunos
    {
        public alunos()
        {
            this.alunos_pessoais = new HashSet<alunos_pessoais>();
            this.alunos_turmas = new HashSet<alunos_turmas>();
        }
    
        public long inep_escola { get; set; }
        public long inep_aluno { get; set; }
        public string codigo_aluno { get; set; }
        public string nome_aluno { get; set; }
        public Nullable<System.DateTime> data_nasc_aluno { get; set; }
        public Nullable<bool> sexo_aluno { get; set; }
        public Nullable<int> cor_raca_aluno { get; set; }
        public Nullable<bool> possui_filiacao_aluno { get; set; }
        public string filiacao1_aluno { get; set; }
        public string filiacao2_aluno { get; set; }
        public Nullable<long> nacionalidade_aluno { get; set; }
        public Nullable<int> pais_origem_aluno { get; set; }
        public Nullable<int> uf_nasc_aluno { get; set; }
        public Nullable<int> municipio_nasc_aluno { get; set; }
        public Nullable<bool> possui_deficiencia_aluno { get; set; }
        public Nullable<bool> defic_cegueira_aluno { get; set; }
        public Nullable<bool> defic_baixa_visao_aluno { get; set; }
        public Nullable<bool> defic_surdez_aluno { get; set; }
        public Nullable<bool> defic_defic_auditiva_aluno { get; set; }
        public Nullable<bool> defic_surdocegueira_aluno { get; set; }
        public Nullable<bool> defic_defic_fisica_aluno { get; set; }
        public Nullable<bool> defic_defic_intelectual_aluno { get; set; }
        public Nullable<bool> defic_defic_multipla_aluno { get; set; }
        public Nullable<bool> defic_autismo_aluno { get; set; }
        public Nullable<bool> defic_asperger_aluno { get; set; }
        public Nullable<bool> defic_rett_aluno { get; set; }
        public Nullable<bool> defic_superdotacao_aluno { get; set; }
        public Nullable<bool> auxilio_ledor_aluno { get; set; }
        public Nullable<bool> auxilio_transcricao { get; set; }
        public Nullable<bool> guia_interprete { get; set; }
        public Nullable<bool> interprete_libras { get; set; }
        public Nullable<bool> leitura_labial { get; set; }
        public Nullable<bool> prova_ampliada_fonte16 { get; set; }
        public Nullable<bool> prova_ampliada_fonte20 { get; set; }
        public Nullable<bool> prova_ampliada_fonte24 { get; set; }
        public Nullable<bool> prova_braile { get; set; }
        public Nullable<bool> prova_especial_nehum { get; set; }
    
        public virtual escolas escolas { get; set; }
        public virtual ICollection<alunos_pessoais> alunos_pessoais { get; set; }
        public virtual ICollection<alunos_turmas> alunos_turmas { get; set; }
    }
}
