//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportCenso.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursos_superior
    {
        public long idcursos_superior { get; set; }
        public string nome_curso { get; set; }
        public string grau_academico { get; set; }
        public Nullable<int> codigo_area { get; set; }
    }
}
