//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportCenso.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class escolas
    {
        public escolas()
        {
            this.alunos = new HashSet<alunos>();
            this.alunos_turmas = new HashSet<alunos_turmas>();
            this.alunos_pessoais = new HashSet<alunos_pessoais>();
            this.profissionais_pessoais = new HashSet<profissionais_pessoais>();
            this.turmas = new HashSet<turmas>();
            this.turmas_pedagogico = new HashSet<turmas_pedagogico>();
        }
    
        public long inep_escola { get; set; }
        public string cpf_gestor { get; set; }
        public string nome_gestor { get; set; }
        public Nullable<bool> cargo_gestor { get; set; }
        public string email_gestor { get; set; }
        public Nullable<int> situacao_escola { get; set; }
        public Nullable<System.DateTime> inicio_letivo { get; set; }
        public Nullable<System.DateTime> final_letivo { get; set; }
        public string nome_escola { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string cep { get; set; }
        public string endereco { get; set; }
        public string endereco_numero { get; set; }
        public string endereco_complemento { get; set; }
        public string bairro { get; set; }
        public Nullable<long> uf_escola { get; set; }
        public Nullable<long> municipio_escola { get; set; }
        public Nullable<long> distrito_escola { get; set; }
        public Nullable<sbyte> DDD_escola { get; set; }
        public string telefone { get; set; }
        public string telefone_publico { get; set; }
        public string telefone_outro { get; set; }
        public string fax_escola { get; set; }
        public string email_escola { get; set; }
        public string cod_regional_ensino { get; set; }
        public Nullable<bool> depend_adm { get; set; }
        public Nullable<bool> localizacao_escola { get; set; }
        public string escolacol { get; set; }
        public Nullable<bool> categoria_privada { get; set; }
        public Nullable<bool> coneniada { get; set; }
        public Nullable<bool> mantenedora_privada1 { get; set; }
        public Nullable<bool> mantenedora_privada2 { get; set; }
        public Nullable<bool> mantenedora_privada3 { get; set; }
        public Nullable<bool> mantenedora_privada4 { get; set; }
        public Nullable<bool> mantenedora_privada5 { get; set; }
        public string cnpj_mantenedora { get; set; }
        public string cnpj_privada { get; set; }
        public Nullable<bool> autorizacao_escola { get; set; }
        public Nullable<bool> unidade_vinculada { get; set; }
        public Nullable<long> cod_escola_sede { get; set; }
        public Nullable<long> cod_ies { get; set; }
    
        public virtual ICollection<alunos> alunos { get; set; }
        public virtual ICollection<alunos_turmas> alunos_turmas { get; set; }
        public virtual ICollection<alunos_pessoais> alunos_pessoais { get; set; }
        public virtual predios predios { get; set; }
        public virtual ICollection<profissionais_pessoais> profissionais_pessoais { get; set; }
        public virtual ICollection<turmas> turmas { get; set; }
        public virtual ICollection<turmas_pedagogico> turmas_pedagogico { get; set; }
    }
}
