//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportCenso.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class predios
    {
        public long inep_escola { get; set; }
        public Nullable<bool> predio_escola { get; set; }
        public Nullable<bool> tempo_igreja { get; set; }
        public Nullable<bool> sala_empresa { get; set; }
        public Nullable<bool> casa_professor { get; set; }
        public Nullable<bool> sala_outra_escola { get; set; }
        public Nullable<bool> unid_socioeduc { get; set; }
        public Nullable<bool> unid_prisional { get; set; }
        public Nullable<bool> local_outros { get; set; }
        public Nullable<bool> ocupacao_predio { get; set; }
        public Nullable<bool> compartilhado { get; set; }
        public Nullable<int> escola_compartilha1 { get; set; }
        public Nullable<int> escola_compartilha2 { get; set; }
        public Nullable<int> escola_compartilha3 { get; set; }
        public Nullable<int> escola_compartilha4 { get; set; }
        public Nullable<int> escola_compartilha5 { get; set; }
        public Nullable<int> escola_compartilha6 { get; set; }
        public Nullable<bool> agua_consumida { get; set; }
        public Nullable<bool> agua_public { get; set; }
        public Nullable<bool> poco_artes { get; set; }
        public Nullable<bool> cisterna { get; set; }
        public Nullable<bool> fonte_rio { get; set; }
        public Nullable<bool> sem_agua { get; set; }
        public Nullable<bool> energia_publica { get; set; }
        public Nullable<bool> energia_gerador { get; set; }
        public Nullable<bool> energia_outros { get; set; }
        public Nullable<bool> sem_energia { get; set; }
        public Nullable<bool> esgoto_publico { get; set; }
        public Nullable<bool> esgoto_fossa { get; set; }
        public Nullable<bool> sem_esgoto { get; set; }
        public Nullable<bool> lixo_coleta { get; set; }
        public Nullable<bool> lixo_queima { get; set; }
        public Nullable<bool> lixo_outra_area { get; set; }
        public Nullable<bool> lixo_recicla { get; set; }
        public Nullable<bool> lixo_enterra { get; set; }
        public Nullable<bool> lixo_outro { get; set; }
        public Nullable<bool> sala_diretoria { get; set; }
        public Nullable<bool> sala_professores { get; set; }
        public Nullable<bool> sala_secretaria { get; set; }
        public Nullable<bool> labo_iformatica { get; set; }
        public Nullable<bool> labo_ciencias { get; set; }
        public Nullable<bool> sala_recursos { get; set; }
        public Nullable<bool> quadra_esportes_coberta { get; set; }
        public Nullable<bool> quadra_esportes_aberta { get; set; }
        public Nullable<bool> cozinha { get; set; }
        public Nullable<bool> biblioteca { get; set; }
        public Nullable<bool> sala_leitura { get; set; }
        public Nullable<bool> parque_infantil { get; set; }
        public Nullable<bool> bercario { get; set; }
        public Nullable<bool> banheiro_fora { get; set; }
        public Nullable<bool> banheiro_dentro { get; set; }
        public Nullable<bool> banheiro_inantil { get; set; }
        public Nullable<bool> banheiro_deficiente { get; set; }
        public Nullable<bool> dependecia_via_deficiente { get; set; }
        public Nullable<bool> banheiro_com_chuveiro { get; set; }
        public Nullable<bool> refeitorio { get; set; }
        public Nullable<bool> despensa { get; set; }
        public Nullable<bool> almoxarifado { get; set; }
        public Nullable<bool> auditorio { get; set; }
        public Nullable<bool> patio_coberto { get; set; }
        public Nullable<bool> patio_descoberto { get; set; }
        public Nullable<bool> alojamento_aluno { get; set; }
        public Nullable<bool> alojamento_professor { get; set; }
        public Nullable<bool> area_verde { get; set; }
        public Nullable<bool> lavanderia { get; set; }
        public Nullable<bool> nenhuma_relaciona { get; set; }
        public Nullable<int> num_salas_aula { get; set; }
        public Nullable<int> num_salas_aula_dentro_fora { get; set; }
        public Nullable<int> qtde_tvs { get; set; }
        public Nullable<int> qtde_videocassete { get; set; }
        public Nullable<int> qtde_dvd { get; set; }
        public Nullable<int> qtde_parabolica { get; set; }
        public Nullable<int> qtde_copiador { get; set; }
        public Nullable<int> qtde_retroprojetor { get; set; }
        public Nullable<int> qtde_impressora { get; set; }
        public Nullable<int> qtde_som { get; set; }
        public Nullable<int> qtde_projetor { get; set; }
        public Nullable<int> qtde_fax { get; set; }
        public Nullable<int> qtde_maq_foto { get; set; }
        public Nullable<int> qtde_computadores_total { get; set; }
        public Nullable<int> qtde_computoadores_administ { get; set; }
        public Nullable<int> qtde_computadores_alunos { get; set; }
        public Nullable<bool> acesso_internet { get; set; }
        public Nullable<bool> banda_larga { get; set; }
        public Nullable<int> total_funcionarios { get; set; }
        public Nullable<bool> alimento_alunos { get; set; }
        public Nullable<bool> aee { get; set; }
        public Nullable<bool> atividade_complementar { get; set; }
        public Nullable<bool> ensino_regular { get; set; }
        public Nullable<bool> educacao_especial { get; set; }
        public Nullable<bool> eja { get; set; }
        public Nullable<bool> educacao_profissional { get; set; }
        public Nullable<bool> ciclos { get; set; }
        public Nullable<bool> localizacao_diferenciada { get; set; }
        public Nullable<bool> material_didatico_nao_utiliza { get; set; }
        public Nullable<bool> material_didatico_quilombola { get; set; }
        public Nullable<bool> material_didatico_indigena { get; set; }
        public Nullable<bool> escola_indigena { get; set; }
        public Nullable<bool> lingua_indigena { get; set; }
        public Nullable<bool> lingua_portuguesa { get; set; }
        public Nullable<int> cod_lingua_indigena { get; set; }
        public Nullable<bool> turmas_brasil_alfabetizado { get; set; }
        public Nullable<bool> escola_aberta { get; set; }
        public Nullable<bool> proposta_pedag_alternancia { get; set; }
    
        public virtual escolas escolas { get; set; }
    }
}
