//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportCenso.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class profissionais_pessoais
    {
        public profissionais_pessoais()
        {
            this.profissionais_formacao = new HashSet<profissionais_formacao>();
            this.turmas = new HashSet<turmas>();
        }
    
        public long inep_escola { get; set; }
        public long inep_profissional { get; set; }
        public string codigo_profissional { get; set; }
        public string nome_profissional { get; set; }
        public string email_profissional { get; set; }
        public Nullable<int> nis_profissional { get; set; }
        public Nullable<System.DateTime> data_nasc_profissional { get; set; }
        public Nullable<bool> sexo_profissional { get; set; }
        public Nullable<int> cor_raca_profissional { get; set; }
        public Nullable<int> filiacao_profissional { get; set; }
        public string filiacao1_profissional { get; set; }
        public string filiacao2_profissional { get; set; }
        public Nullable<int> nacionalidade_profissional { get; set; }
        public Nullable<int> pais_origem_profissional { get; set; }
        public Nullable<int> uf_nasci__profissional { get; set; }
        public Nullable<int> municipio_nasci_profissional { get; set; }
        public Nullable<bool> deficiencia_profissional { get; set; }
        public Nullable<bool> cegueira_profissional { get; set; }
        public Nullable<bool> baixa_visao_profissional { get; set; }
        public Nullable<bool> surdez_profissional { get; set; }
        public Nullable<bool> defic_auditiva_profissional { get; set; }
        public Nullable<bool> surdocegueira_profissional { get; set; }
        public Nullable<bool> defic_fisica_profissional { get; set; }
        public Nullable<bool> defic_intelec_profissional { get; set; }
        public Nullable<bool> defic_multipla_profissional { get; set; }
    
        public virtual escolas escolas { get; set; }
        public virtual ICollection<profissionais_formacao> profissionais_formacao { get; set; }
        public virtual profissionais_moradia profissionais_moradia { get; set; }
        public virtual ICollection<turmas> turmas { get; set; }
    }
}
