//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportCenso.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class profissionais_moradia
    {
        public Nullable<int> inep_escola { get; set; }
        public long inep_profissional { get; set; }
        public string codigo_profissional { get; set; }
        public string cpf_profissional { get; set; }
        public Nullable<bool> local_residencia { get; set; }
        public string cep_profissional { get; set; }
        public string endereco_profissional { get; set; }
        public string num_endereco_profissional { get; set; }
        public string complemento_profissional { get; set; }
        public string bairro_profissional { get; set; }
        public Nullable<int> uf_profissional { get; set; }
        public Nullable<int> municipio_profissional { get; set; }
    
        public virtual profissionais_pessoais profissionais_pessoais { get; set; }
    }
}
