//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportCenso.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class turmas_pedagogico
    {
        public long inep_turam { get; set; }
        public Nullable<long> inep_escola { get; set; }
        public string codigo_turma { get; set; }
        public string nome_turma { get; set; }
        public Nullable<bool> mediacao_didatico_pedagogica { get; set; }
        public string horario_inicial_hora { get; set; }
        public string horiario_inicial_minuto { get; set; }
        public string horario_final_hora { get; set; }
        public string horario_final_minuto { get; set; }
        public bool semana_domingo { get; set; }
        public bool semana_segunda { get; set; }
        public bool semana_terca { get; set; }
        public bool semana_quarta { get; set; }
        public bool semana_quinta { get; set; }
        public bool semana_sexta { get; set; }
        public bool semana_sabado { get; set; }
        public int tipo_atendimento { get; set; }
        public int turma_mais_educacao { get; set; }
        public int tipo_atividade1 { get; set; }
        public int tipo_atividade2 { get; set; }
        public int tipo_atividade3 { get; set; }
        public int tipo_atividade4 { get; set; }
        public int tipo_atividade5 { get; set; }
        public int tipo_atividade6 { get; set; }
        public bool ensino_braile { get; set; }
        public bool ensino_recurso_optico { get; set; }
        public bool ensino_orienta_mobilidade { get; set; }
        public bool ensino_libras { get; set; }
        public bool ensino_caa { get; set; }
        public bool enriquecimento_curricular { get; set; }
        public bool soroban { get; set; }
        public bool informatica_acessivel { get; set; }
        public bool ensino_lingua_portuguesa { get; set; }
        public bool autonomia_ambiente_escolar { get; set; }
        public int etapa_ensino { get; set; }
        public int codigo_curso_tecnico { get; set; }
        public int disciplina_quimica { get; set; }
        public int disciplina_fisica { get; set; }
        public int disciplina_matematica { get; set; }
        public int disciplina_biologia { get; set; }
        public int disciplina_ciencias { get; set; }
        public int disciplina_lingua_portug { get; set; }
        public int disciplina_lingua_ingles { get; set; }
        public int disciplina_lingua_espanhol { get; set; }
        public int disciplina_lingua_frances { get; set; }
        public int disciplina_lingua_outra { get; set; }
        public int disciplina_artes { get; set; }
        public int disciplina_ed_fisica { get; set; }
        public int disciplina_historia { get; set; }
        public int disciplina_geografia { get; set; }
        public int disciplina_filosofia { get; set; }
        public int disciplina_estudos_sociais { get; set; }
        public int disciplina_sociologia { get; set; }
        public int disciplina_informatica { get; set; }
        public int disciplina_profissionalizante { get; set; }
        public int disciplina_atend_especial { get; set; }
        public int disciplina_diversidade { get; set; }
        public int disciplina_libras { get; set; }
        public int disciplina_pedagogica { get; set; }
        public int disciplina_ensino_religioso { get; set; }
        public int disciplina_lingua_indigena { get; set; }
        public int disciplina_outra { get; set; }
    
        public virtual escolas escolas { get; set; }
        public virtual turmas turmas { get; set; }
    }
}
