//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportCenso.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class turmas
    {
        public long inep_escola { get; set; }
        public long inep_profissional { get; set; }
        public Nullable<int> codigo_profissional { get; set; }
        public long inep_turma { get; set; }
        public Nullable<int> codigo_turma { get; set; }
        public Nullable<int> funcao_turma { get; set; }
        public Nullable<int> situacao_funcional_turma { get; set; }
        public Nullable<int> disciplina_turma { get; set; }
        public Nullable<int> disciplina_turma2 { get; set; }
        public Nullable<int> disciplina_turma3 { get; set; }
        public Nullable<int> disciplina_turma4 { get; set; }
        public Nullable<int> disciplina_turma5 { get; set; }
        public Nullable<int> disciplina_turma6 { get; set; }
        public Nullable<int> disciplina_turma7 { get; set; }
        public Nullable<int> disciplina_turma8 { get; set; }
        public Nullable<int> disciplina_turma9 { get; set; }
        public Nullable<int> disciplina_turma10 { get; set; }
        public Nullable<int> disciplina_turma11 { get; set; }
        public Nullable<int> disciplina_turma12 { get; set; }
        public Nullable<int> disciplina_turma13 { get; set; }
    
        public virtual alunos_turmas alunos_turmas { get; set; }
        public virtual escolas escolas { get; set; }
        public virtual profissionais_pessoais profissionais_pessoais { get; set; }
        public virtual turmas_pedagogico turmas_pedagogico { get; set; }
    }
}
